# Generated by Django 6.0.4 on 2026-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
